name: Check Token

on:
  push:
    branches:
      - main

jobs:
  check-token:
    runs-on: ubuntu-latest

    steps:
      - name: Check for token
        run: |
          grep -r -e 'token' -e 'certificate' -e 'key' .
