name: Check Token

on:
  push:
    branches:
      - main

jobs:
  check-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Search for token
        run: |
          grep -r -l "token" .
